# Generated by Django 4.1.7 on 2023-04-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_logos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logos',
            options={'verbose_name_plural': 'Logo'},
        ),
    ]
