# Generated by Django 4.1.7 on 2023-04-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_logos_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logos',
        ),
    ]
