# Generated by Django 4.1.7 on 2023-04-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_issued_items_is_accepted_issued_items_is_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issued_items',
            old_name='is_accepted',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='issued_items',
            old_name='is_rejected',
            new_name='rejected',
        ),
    ]
