# Generated by Django 4.1.7 on 2023-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_issued_items_status_remove_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_items',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
